[package]
name = "me/default"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# https://sleitnick.github.io/Knit/
Knit = "sleitnick/knit@1.4.7"

#https://sleitnick.github.io/RbxUtil/
Component = "sleitnick/component@2.4.5"
Input = "sleitnick/input@1.3.3"	
Loader = "sleitnick/loader@1.0.2"
Signal = "sleitnick/signal@1.1.0"	
Streamable = "sleitnick/streamable@1.2.3"	
# TableUtil = "sleitnick/table-util@1.1.1"	
Timer = "sleitnick/timer@1.1.1"	
Silo = "sleitnick/silo@0.1.0"	
Symbol = "sleitnick/symbol@2.0.0"	

# https://eryn.io/roblox-lua-promise/
Promise = "evaera/promise@4.0.0"

# https://howmanysmall.github.io/Janitor/
Janitor = "howmanysmall/janitor@1.14.1"

# https://elttob.github.io/Fusion/
Fusion = "elttob/fusion@0.1.1-beta"

# https://github.com/csqrl/sift
sift = "csqrl/sift@0.0.2"

# https://github.com/Roblox/rodux
# rodux = "roblox/rodux@3.0.0"